# Numpy


About Numpy



In [1]:
import numpy as np

In [6]:
# cast a list into a numpy array
ls = [1,2,3]

In [3]:
type(np.array(ls))

numpy.ndarray

In [4]:
arr = np.array(ls)

In [5]:
arr

array([1, 2, 3])

In [9]:
# Built in NP functions
#range
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# make steps in numbers Example: By 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
# Create array of zeros Example creating Nd array
np.zeros((3,5))


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [14]:
# Create array of ones Example creating Nd array
np.ones((3,7))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [16]:
# Linear spaced array take start and stop point and evening space between
np.linspace(0,11,10)

array([  0.        ,   1.22222222,   2.44444444,   3.66666667,
         4.88888889,   6.11111111,   7.33333333,   8.55555556,
         9.77777778,  11.        ])

In [17]:
# Random 
np.random.randint(0,10)

4

In [18]:
np.random.randint(0,10,(5,5))

array([[8, 6, 3, 8, 3],
       [7, 4, 5, 4, 9],
       [5, 3, 9, 3, 8],
       [0, 7, 3, 1, 6],
       [8, 7, 7, 8, 2]])

In [19]:
#random Seed
np.random.seed(5)
np.random.randint(0,10)

3

In [20]:
#random Seed
np.random.seed(5)
np.random.randint(0,10)

3

In [21]:
np.random.seed(5)
arr = np.random.randint(0,10,10)

In [22]:
arr

array([3, 6, 6, 0, 9, 8, 4, 7, 0, 0])

In [24]:
arr.max()

9

In [25]:
arr.min()

0

In [26]:
arr.mean()

4.2999999999999998

In [27]:
arr.argmax()


4

In [28]:
arr.argmin()

3

In [29]:
math = np.arange(0,100).reshape(10,10)

In [30]:
math

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [38]:
#access Numbers ro, columns
math[3,4]

34

In [36]:
math[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
math[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [40]:
math[0:5,0:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [41]:
# matrix
math > 60



array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

In [42]:
filter_60 = math > 60
math[filter_60]

array([61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [43]:
math[math>60]

array([61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])